In [ ]:
import pandas as pd
import numpy as np
import os
import base64
from pathlib import Path
import random
from base64 import urlsafe_b64encode, urlsafe_b64decode

In [21]:
df=pd.read_csv('Data/Data for Malware Query Generation/malicious_phish.csv')
card_data_encoded=pd.read_csv('Data/Data for Malware Query Generation/card_data.csv')

### The encoded credit card information used in 'card_data.csv' was generated by using a golang script based on the logic described in https://www.gdatasoftware.com/blog/2014/10/23942-new-frameworkpos-variant-exfiltrates-data-via-dns-requests.

###  

*   The 'framework_pos.go' file was used to manually create dummy encoded credit card records. 
* The credit card numbers were taken as an input to convert it into an encoded format to finally form a DNS Query by concatenating it with a malacious URL.

In [23]:
card_data_encoded

               cardno                            encode
0    8638540736318190  cac4c1cac7c6c2c5c1c4c1c3cac3cbc4
1    7106423970931510  c5c3c2c4c6c0c1cbc5c2cbc1c3c7c3c7
2    6492565582413530  c4c6cbc0c7c4c7c7cac0c6c3c1c7c1c2
3    2868560651525700  c0cac4cac7c4c2c4c7c3c7c0c7c5c2c4
4    1438690625098210  c3c6c1cac4cbc2c4c0c7c2cbcac0c3cb
..                ...                               ...
495  3168655299361500  c7cbc5cacac6c6cbc3c3c1cbc6c7c4c7
496  4012777466907050  c6c2c3c0c5c5c5c6c4c4cbc2c5c2c7c2
497  7677593726713680  c5c4c5c5c7cbc1c5c0c4c5c3c1c4cac2
498  9458113053336470  c6c2c6c2c5c6c4c6c6c2c2c2a1c6c6c5
499  5583975160865670  c6c2c6c2c5c6c4c6c7c2c2c2c1c6c6ca

[500 rows x 2 columns]

In [ ]:
pd.DataFrame(np.repeat(card_data_encoded.values, 25, axis=0))

                       0                                 1
0    8638-5407-3631-8196  cac4c1cac7c6c2c5c1c4c1c3cac3cbc4
1    8638-5407-3631-8196  cac4c1cac7c6c2c5c1c4c1c3cac3cbc4
2    8638-5407-3631-8196  cac4c1cac7c6c2c5c1c4c1c3cac3cbc4
3    8638-5407-3631-8196  cac4c1cac7c6c2c5c1c4c1c3cac3cbc4
4    8638-5407-3631-8196  cac4c1cac7c6c2c5c1c4c1c3cac3cbc4
..                   ...                               ...
620  6557-2662-6932-6028  c4c7c7c5c0c4c4c0c4cbc1c0c4c2c0ca
621  6557-2662-6932-6028  c4c7c7c5c0c4c4c0c4cbc1c0c4c2c0ca
622  6557-2662-6932-6028  c4c7c7c5c0c4c4c0c4cbc1c0c4c2c0ca
623  6557-2662-6932-6028  c4c7c7c5c0c4c4c0c4cbc1c0c4c2c0ca
624  6557-2662-6932-6028  c4c7c7c5c0c4c4c0c4cbc1c0c4c2c0ca

[625 rows x 2 columns]

In [24]:
df_malware=df.loc[(df['type'] =='malware')]

In [25]:
df_malware

                                                      url     type
38      http://www.824555.com/app/member/SportOption.p...  malware
115     http://9779.info/%E5%84%BF%E7%AB%A5%E7%AB%8B%E...  malware
156     http://9779.info/%E6%A0%91%E5%8F%B6%E7%B2%98%E...  malware
212     http://9779.info/%E5%8F%A4%E4%BB%A3%E4%BA%8C%E...  malware
240     http://chinacxyy.com/piccodejs-000.asp?lm2=191...  malware
...                                                   ...      ...
120698  http://www.mt6669.com/cl/tpl/montecarlo/ver1/c...  malware
120803  http://9779.info/%E6%95%99%E5%B8%88%E6%89%8B%E...  malware
120839  http://clients.flatearth.co.uk/lawfirms2013/da...  malware
120850  http://chinacxyy.com/piccodejs-000.asp?lm2=189...  malware
120876  http://www.thereefrestaurant.com/wp-content/pl...  malware

[2921 rows x 2 columns]

In [26]:
str_rem='http://'
df_malware['url'] = df_malware['url'].str.replace(str_rem, '')
df_malware['url'] = df_malware['url'].str.replace('www.', '')

df_malware

<ipython-input-26-7b3498b38143>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_malware['url'] = df_malware['url'].str.replace(str_rem, '')
<ipython-input-26-7b3498b38143>:3: FutureWarning: The default value of regex will change from True to False in a future version.
  df_malware['url'] = df_malware['url'].str.replace('www.', '')
<ipython-input-26-7b3498b38143>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_malware['url'] = df_malware['url'].str.replace('www.', '')

                                                      url     type
38      824555.com/app/member/SportOption.php?uid=gues...  malware
115     9779.info/%E5%84%BF%E7%AB%A5%E7%AB%8B%E4%BD%93...  malware
156     9779.info/%E6%A0%91%E5%8F%B6%E7%B2%98%E8%B4%B4...  malware
212     9779.info/%E5%8F%A4%E4%BB%A3%E4%BA%8C%E5%8D%81...  malware
240     chinacxyy.com/piccodejs-000.asp?lm2=191&x=3&y=...  malware
...                                                   ...      ...
120698  mt6669.com/cl/tpl/montecarlo/ver1/css/montecar...  malware
120803  9779.info/%E6%95%99%E5%B8%88%E6%89%8B%E5%B7%A5...  malware
120839  clients.flatearth.co.uk/lawfirms2013/dashboard...  malware
120850  chinacxyy.com/piccodejs-000.asp?lm2=189&x=3&y=...  malware
120876  thereefrestaurant.com/wp-content/plugins/light...  malware

[2921 rows x 2 columns]

In [27]:
df_malware=df_malware.head(500)
url_dataset=df_malware['url']
url_dataset

38       824555.com/app/member/SportOption.php?uid=gues...
115      9779.info/%E5%84%BF%E7%AB%A5%E7%AB%8B%E4%BD%93...
156      9779.info/%E6%A0%91%E5%8F%B6%E7%B2%98%E8%B4%B4...
212      9779.info/%E5%8F%A4%E4%BB%A3%E4%BA%8C%E5%8D%81...
240      chinacxyy.com/piccodejs-000.asp?lm2=191&x=3&y=...
                               ...
20373    wanwang.aliyun.com/domain/searchresult/?domain...
20380    wxztjz.com/e/public/onclick?enews=donews&class...
20415             joeandjesscomicstrip.com/images/joea.exe
20437    facebook.com/plugins/likebox.php?href=http%3A%...
20496    chinesevie.com/index.php?option=com_content&vi...
Name: url, Length: 500, dtype: object

In [28]:
print(len(df_malware[
    df_malware["url"].apply(lambda x: len(x) < 50)
]))
df_malware_without_extra_char=df_malware[
    df_malware["url"].apply(lambda x: len(x) < 50)
]
df_malware_without_extra_char
df_new = pd.DataFrame(np.repeat(df_malware_without_extra_char.values, 10, axis=0))
df_new
df_final=df_new.head(500)
df_final

59

                    0        1
0         trtsport.cz  malware
1         trtsport.cz  malware
2         trtsport.cz  malware
3         trtsport.cz  malware
4         trtsport.cz  malware
..                ...      ...
495  energy-utama.com  malware
496  energy-utama.com  malware
497  energy-utama.com  malware
498  energy-utama.com  malware
499  energy-utama.com  malware

[500 rows x 2 columns]

In [32]:
df_malware=df_malware.reset_index(drop=True)
print(df_malware)
card_data_encoded["data_combined"] = card_data_encoded['encode'].astype(str) +"."+ df_final[0]
card_data_encoded

                                                   url     type
0    824555.com/app/member/SportOption.php?uid=gues...  malware
1    9779.info/%E5%84%BF%E7%AB%A5%E7%AB%8B%E4%BD%93...  malware
2    9779.info/%E6%A0%91%E5%8F%B6%E7%B2%98%E8%B4%B4...  malware
3    9779.info/%E5%8F%A4%E4%BB%A3%E4%BA%8C%E5%8D%81...  malware
4    chinacxyy.com/piccodejs-000.asp?lm2=191&x=3&y=...  malware
..                                                 ...      ...
495  wanwang.aliyun.com/domain/searchresult/?domain...  malware
496  wxztjz.com/e/public/onclick?enews=donews&class...  malware
497           joeandjesscomicstrip.com/images/joea.exe  malware
498  facebook.com/plugins/likebox.php?href=http%3A%...  malware
499  chinesevie.com/index.php?option=com_content&vi...  malware

[500 rows x 2 columns]

,cardno,encode,data_combined
0,8638540736318190,cac4c1cac7c6c2c5c1c4c1c3cac3cbc4,cac4c1cac7c6c2c5c1c4c1c3cac3cbc4.trtsport.cz
1,7106423970931510,c5c3c2c4c6c0c1cbc5c2cbc1c3c7c3c7,c5c3c2c4c6c0c1cbc5c2cbc1c3c7c3c7.trtsport.cz
2,6492565582413530,c4c6cbc0c7c4c7c7cac0c6c3c1c7c1c2,c4c6cbc0c7c4c7c7cac0c6c3c1c7c1c2.trtsport.cz
3,2868560651525700,c0cac4cac7c4c2c4c7c3c7c0c7c5c2c4,c0cac4cac7c4c2c4c7c3c7c0c7c5c2c4.trtsport.cz
4,1438690625098210,c3c6c1cac4cbc2c4c0c7c2cbcac0c3cb,c3c6c1cac4cbc2c4c0c7c2cbcac0c3cb.trtsport.cz
...,...,...,...
495,3168655299361500,c7cbc5cacac6c6cbc3c3c1cbc6c7c4c7,c7cbc5cacac6c6cbc3c3c1cbc6c7c4c7.energy-utama.com
496,4012777466907050,c6c2c3c0c5c5c5c6c4c4cbc2c5c2c7c2,c6c2c3c0c5c5c5c6c4c4cbc2c5c2c7c2.energy-utama.com
497,7677593726713680,c5c4c5c5c7cbc1c5c0c4c5c3c1c4cac2,c5c4c5c5c7cbc1c5c0c4c5c3c1c4cac2.energy-utama.com
498,9458113053336470,c6c2c6c2c5c6c4c6c6c2c2c2a1c6c6c5,c6c2c6c2c5c6c4c6c6c2c2c2a1c6c6c5.energy-utama.com
499,5583975160865670,c6c2c6c2c5c6c4c6c7c2c2c2c1c6c6ca,c6c2c6c2c5c6c4c6c7c2c2c2c1c6c6ca.energy-utama.com

In [33]:
card_data_encoded.insert(2, 'attack', 1)
card_data_encoded

,cardno,encode,attack,data_combined
0,8638540736318190,cac4c1cac7c6c2c5c1c4c1c3cac3cbc4,1,cac4c1cac7c6c2c5c1c4c1c3cac3cbc4.trtsport.cz
1,7106423970931510,c5c3c2c4c6c0c1cbc5c2cbc1c3c7c3c7,1,c5c3c2c4c6c0c1cbc5c2cbc1c3c7c3c7.trtsport.cz
2,6492565582413530,c4c6cbc0c7c4c7c7cac0c6c3c1c7c1c2,1,c4c6cbc0c7c4c7c7cac0c6c3c1c7c1c2.trtsport.cz
3,2868560651525700,c0cac4cac7c4c2c4c7c3c7c0c7c5c2c4,1,c0cac4cac7c4c2c4c7c3c7c0c7c5c2c4.trtsport.cz
4,1438690625098210,c3c6c1cac4cbc2c4c0c7c2cbcac0c3cb,1,c3c6c1cac4cbc2c4c0c7c2cbcac0c3cb.trtsport.cz
...,...,...,...,...
495,3168655299361500,c7cbc5cacac6c6cbc3c3c1cbc6c7c4c7,1,c7cbc5cacac6c6cbc3c3c1cbc6c7c4c7.energy-utama.com
496,4012777466907050,c6c2c3c0c5c5c5c6c4c4cbc2c5c2c7c2,1,c6c2c3c0c5c5c5c6c4c4cbc2c5c2c7c2.energy-utama.com
497,7677593726713680,c5c4c5c5c7cbc1c5c0c4c5c3c1c4cac2,1,c5c4c5c5c7cbc1c5c0c4c5c3c1c4cac2.energy-utama.com
498,9458113053336470,c6c2c6c2c5c6c4c6c6c2c2c2a1c6c6c5,1,c6c2c6c2c5c6c4c6c6c2c2c2a1c6c6c5.energy-utama.com
499,5583975160865670,c6c2c6c2c5c6c4c6c7c2c2c2c1c6c6ca,1,c6c2c6c2c5c6c4c6c7c2c2c2c1c6c6ca.energy-utama.com

In [35]:
os.makedirs('outputs', exist_ok=True)  
card_data_encoded.to_csv('data/Data for Malware Query Generation/output.csv')